### Import numpy library  

In [2]:
import numpy as np

### Create an Array using array function  

In [5]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


### Create an Array containing numbers from 20 to 40 

In [7]:
arr2 = np.arange(20,41)
print(arr2)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


### Create an array which contain 10 elements and every element is 5  

In [10]:
fives = np.ones(10, dtype = int)*5
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### create a 1-d array and then convert it into 3-d array  

In [13]:
arr3 = np.random.randint(1,50,24).reshape(3,4,2) # 3x4x2 = 24
arr3

array([[[27, 26],
        [ 7, 29],
        [20, 34],
        [25, 39]],

       [[24, 43],
        [ 2, 37],
        [ 5, 13],
        [42, 21]],

       [[37, 23],
        [40, 46],
        [17,  6],
        [37, 10]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [15]:
arr4 = np.random.rand(5,5)
arr4

array([[0.65268306, 0.71713349, 0.98413465, 0.08889256, 0.81270087],
       [0.24309531, 0.94451624, 0.21723472, 0.178789  , 0.55866708],
       [0.68408471, 0.16657007, 0.55002938, 0.75465265, 0.07493738],
       [0.26460464, 0.5362202 , 0.79175734, 0.25316291, 0.38510205],
       [0.90767934, 0.91066281, 0.79661403, 0.60585689, 0.58515472]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [20]:
np.random.seed(123)
arr5 = np.random.randint(1,50,20)
arr5[arr5%2 == 0] = -1
arr5

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [22]:
matrix = np.array([[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]])
matrix[1:3, 0:3]

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [23]:
arr7 = np.array([1,2,3])
arr8 = np.array([4,5,6])
np.hstack((arr7, arr8))

array([1, 2, 3, 4, 5, 6])

### Stack 2-d matrix horizontally and vertically

In [25]:
matrix2 = np.random.randint(1,10,9).reshape(3,3)
matrix3 = np.random.randint(10,20,9).reshape(3,3)
matrix2

array([[7, 2, 6],
       [7, 3, 2],
       [9, 4, 6]])

In [26]:
matrix3

array([[10, 12, 16],
       [12, 14, 14],
       [16, 13, 10]])

In [27]:
np.hstack((matrix2, matrix3))

array([[ 7,  2,  6, 10, 12, 16],
       [ 7,  3,  2, 12, 14, 14],
       [ 9,  4,  6, 16, 13, 10]])

In [28]:
np.vstack((matrix2, matrix3))

array([[ 7,  2,  6],
       [ 7,  3,  2],
       [ 9,  4,  6],
       [10, 12, 16],
       [12, 14, 14],
       [16, 13, 10]])