In [1]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [3]:
type(array_1d)

numpy.ndarray

In [4]:
array_1d.ndim

1

In [5]:
array_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
array_2d.ndim

2

In [7]:
array_1d.size

4

In [8]:
array_2d.size

8

In [9]:
array_2d.shape

(2, 4)

In [10]:
array_2d.dtype

dtype('int32')