# Numpy Functions

In [1]:
import numpy as np

# arange()

In [2]:
# np.arrange(start value, end value, step value)
# Creates a 1d array from the start value (inclusive) to the end value (exclusive) in the given range.
ar_1d = np.arange(1, 13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
# Creates a 1d array from 1 to 13 (exclusive) with the step of 2 i.e. dropping 1 integer in between
odd_ar = np.arange(1, 13, 2)
print(odd_ar)

[ 1  3  5  7  9 11]


# reshape()

In [4]:
# Creating a 2d array by reshaping a 1d array. Note that 2*6 = ar_1d.size (length of the 1d array) (in this case its 12)
ar_2d = ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [5]:
# Creating a 3d array by reshaping a 1d array. Note that 2*3*2 = ar_1d.size (length of the 1d array) (in this case its 12)
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
# Combination of arrange and reshape methods
arr = np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [7]:
# Converts a multidimensional array to 1 dimensional array
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [8]:
# Converts a multidimensional array to 1 dimensional array
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [9]:
# Swapping the no. of rows and columns into an array
arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])