In [3]:
import numpy as np
import random

In [6]:
np.random.random(1)

array([0.37059474])

In [12]:
np.random.random((3,3))

array([[2.27639451e-01, 7.80312136e-01, 2.30237287e-01],
       [5.04474284e-01, 4.25170184e-01, 6.37345459e-04],
       [3.58523321e-02, 8.14019571e-01, 2.87047821e-01]])

In [13]:
np.random.randint(1,4)

1

In [14]:
np.random.randint(1,4, (4,4))

array([[2, 2, 2, 3],
       [2, 2, 2, 1],
       [1, 2, 1, 1],
       [1, 1, 2, 2]])

In [16]:
np.random.randint(1,4, (4, 3, 4))

array([[[2, 1, 1, 3],
        [1, 2, 2, 1],
        [1, 2, 3, 1]],

       [[2, 2, 3, 3],
        [3, 1, 1, 3],
        [3, 2, 3, 2]],

       [[3, 2, 1, 1],
        [2, 1, 3, 3],
        [1, 2, 3, 3]],

       [[2, 3, 1, 3],
        [3, 1, 3, 1],
        [3, 3, 1, 3]]])

In [17]:
np.random.seed(10)
np.random.randint(1,4, (4, 3, 4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3]],

       [[1, 2, 1, 3],
        [1, 3, 1, 1],
        [1, 3, 1, 3]],

       [[3, 2, 1, 1],
        [3, 2, 3, 2],
        [2, 2, 2, 3]],

       [[2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]]])

In [19]:
np.random.seed(10)
np.random.randint(1,4, (4, 3, 4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3]],

       [[1, 2, 1, 3],
        [1, 3, 1, 1],
        [1, 3, 1, 3]],

       [[3, 2, 1, 1],
        [3, 2, 3, 2],
        [2, 2, 2, 3]],

       [[2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]]])

In [20]:
np.random.rand(3)

array([0.60103895, 0.8052232 , 0.52164715])

In [31]:
np.random.rand(3,3)

array([[0.7738303 , 0.03995921, 0.42949218],
       [0.31492687, 0.63649114, 0.34634715],
       [0.04309736, 0.87991517, 0.76324059]])

In [32]:
np.random.randn(3,3)

array([[-1.12913125, -0.21578989,  0.98907246],
       [ 0.31475378,  2.46765106, -1.50832149],
       [ 0.62060066, -1.04513254, -0.79800882]])

In [25]:
x = [1,2,3,4]
np.random.choice(x)

3

In [26]:
for i in range(20):
    print(np.random.choice(x))

3
4
1
1
1
1
3
3
2
2
4
1
1
3
2
2
4
2
3
2


In [30]:
np.random.permutation(x)

array([2, 4, 3, 1])